../bin/soak.exe: soak.cpp ../../src/general/hcp.cpp ../../src/general/hcp_toi.cpp
	@mkdir -p ../bin
	g++ -std=c++14 -O2 -o ../bin/soak.exe soak.cpp ../../src/general/hcp.cpp ../../src/general/hcp_toi.cpp -I../../../common -I../../../hcp
